(function(g){var window=this;var r3=function(a){var b={languageCode:a.u,languageName:a.A,displayName:g.$z(a),kind:a.w,name:a.B,id:a.H,is_servable:a.D,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.C};a.o&&(b.translationLanguage=a.o);return b},s3=function(a){return a.o?a.o.languageCode:a.u},kpa=function(a,b){var c=new g.Zz;
c.u=a.u;c.A=a.A;c.B=a.B;c.w=a.w;c.isDefault=!1;c.D=a.D;c.isTranslateable=a.isTranslateable;c.C=a.C;c.G=a.G;c.o=b;return c},lpa=function(){this.u=[];
this.o=[]},t3=function(a,b){return b?a.o.concat(a.u):a.o},u3=function(a,b){switch(b.w){case "asr":var c=a.u;
g.Va(c,(0,g.x)(b.jr,b))||c.push(b);break;default:c=a.o,g.Va(c,(0,g.x)(b.jr,b))||c.push(b)}},v3=function(a){g.A.call(this);
this.Ya=a;this.u=new lpa;this.B=[]},w3=function(a,b,c){v3.call(this,a);
this.o=null;this.B=b.Vu;this.A=c},x3=function(){this.o=[]},y3=function(a,b,c,d,e,f){g.A.call(this);
this.J=a;this.A=b;this.U=b.P();this.B=new x3;this.o=null;this.D=d;this.K=f;this.u=this.w=null;this.N=c;this.C=e||!1;this.G=new g.J(this.fx,1E3,this);g.B(this,this.G);this.H=new g.R(this);g.B(this,this.H);this.H.M(b,"SEEK_COMPLETE",this.Wx);this.Wx();this.fx()},z3=function(a,b){b-=a.A.ub();
var c=a.o;a.o=g.Ta(a.N.Ef(b).o);c!=a.o&&a.K&&a.K()},A3=function(a,b){var c=g.Tw(g.az(b,a.J,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Tp(c,d,3,100).then((0,g.x)(a.yL,a));a.w=b;c=a.B;d=a.w.o[0].u;var e=g.lb(c.o,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.o[e-1]&&e<c.o.length&&1==c.o[e]-d?(g.ab(c.o,e),g.ab(c.o,e-1)):0<e&&1==d-c.o[e-1]?c.o[e-1]=d:e<c.o.length&&1==c.o[e]-d?c.o[e]=d:(g.ib(c.o,e,0,d),g.ib(c.o,e+1,0,d)))},B3=function(a,b){v3.call(this,b.P());
this.o=a;this.D=b;this.A=null;this.w=!1;this.C=g.Jy(this.D.P())&&!this.o.u},C3=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.WQ(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Zz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},mpa=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},D3=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.WQ(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},E3=function(a,b,c,d,e){v3.call(this,e||null);
c=c||g.$o(a).hl||"";c=c.split("_").join("-");this.w=g.bp(a,{hl:c});this.A=b;this.C=!!d;this.D={};this.o=null},F3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.qE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.A=f;this.o=k},G3=function(a,b,c,d,e){g.qE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},I3=function(a){a=void 0===a?{}:a;
var b="_"+H3++;return new G3(0,0x8000000000000,0,b,a)},K3=function(a,b,c,d,e,f){var k={};
g.Pa(k,b);g.Pa(k,a.params);g.Pa(k,c);var l={};g.Pa(l,b.wb);a.params.wb&&g.Pa(l,a.params.wb);g.Pa(l,c.wb);k.wb=l;g.T.call(this,{F:"div",I:"caption-window",O:{id:"caption-window-"+a.id,dir:1==k.xe?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},L:[{F:"span",I:"captions-text",O:{style:"word-wrap: normal; display: block;"}}]});this.G=[];this.V=!1;this.B=a;this.da=this.X=null;this.Ma=e;this.La=f;this.H=null;this.ba=.96*e;this.ya=.96*f;this.w=k;this.Ja=c;this.D=this.u["captions-text"];this.Da=
null!=this.D.style["box-decoration-break"]||null!=this.D.style["-webkit-box-decoration-break"];this.aa=d/360*16;this.type=0;this.oa=this.aa*J3(l);a=new g.WM(this.element,!0);g.B(this,a);a.subscribe("dragstart",this.LG,this);a.subscribe("dragmove",this.KG,this);a.subscribe("dragend",this.JG,this);this.xa=this.ra=0;b="";this.w.windowOpacity&&(a=g.n0(this.w.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.w.windowOpacity+")");a={"background-color":b,display:!1===this.w.isVisible?"none":"","text-align":npa[this.w.textAlign]};
this.Da&&(a["border-radius"]=b?this.oa/8+"px":"");if(this.C=2==this.B.params.xe||3==this.B.params.xe)b=this.element,c="vertical-rl",1==this.w.SA&&(c="vertical-lr"),g.Ed&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.kh(b,"-o-writing-mode",c),g.kh(b,"-webkit-writing-mode",c),g.kh(b,"writing-mode",c),g.kh(b,"text-orientation","upright"),g.L(b,"ytp-vertical-caption"),3==this.B.params.xe&&(g.kh(b,"text-orientation",""),g.kh(b,"transform","rotate(180deg)"));g.kh(this.element,a);switch(this.w.Zf){case 0:case 1:case 2:g.L(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.L(this.element,"ytp-caption-window-bottom")}},J3=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},L3=function(a,b){var c={},d=b.background?b.background:a.w.wb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.w.wb.backgroundOpacity;d=g.n0(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Da&&(c["box-decoration-break"]="clone",c["border-radius"]=a.oa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.aa*J3(b)+"px";d=1;e=b.color||a.w.wb.color;if(b.color||null!=b.textOpacity)e=g.n0(e),d=null==b.textOpacity?a.w.wb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.dv&&(k=e=b.dv);var l=a.aa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Dp()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.w.wb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Re&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.yE&&(c.visibility="hidden");1==b.AE&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.vu||g.Ly,3==a.B.params.xe?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.we||2==b.we||3==b.we||4==b.we||5==b.we)if(g.vu)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.we){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},M3=function(a){a.H=g.Ld("SPAN");
g.kh(a.H,{display:"block"});g.L(a.H,"caption-visual-line");a.D.appendChild(a.H)},N3=function(a,b){var c=g.Ld("SPAN");
g.kh(c,{display:"inline-block","white-space":"pre-wrap"});g.kh(c,L3(a,b));c.classList.add("ytp-caption-segment");a.H.appendChild(c);c.previousElementSibling&&(g.kh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.kh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},O3=function(a,b,c){a.V=a.V||!!c;
var d={};g.Pa(d,a.w.wb);g.Pa(d,c||b.o);g.Pa(d,a.Ja.wb);(c=!a.H)&&M3(a);for(var e=a.X&&a.da&&g.Yb(d,a.da)?a.X:N3(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.A,n=k[l];m&&!c?(M3(a),e=N3(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Md(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.vu||!g.oh(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.oh(n.children[2],"text-emphasis-position")&&(m=a.C?"padding-left":"padding-bottom"),g.Gd?
g.kh(e,m,"1em"):g.kh(e,m,"0.5em")))}a.da=d;a.X=e;a.G.push(b)},P3=function(){},R3=function(){this.w=this.u=this.mode=this.A=0;
this.B=new Q3(this);this.C=new Q3(this);this.o=[];this.clear()},opa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{El:a,
Fl:b,result:0};a=S3[a];b=S3[b];if(a&128){if(!(b&128)&&0!=c.o&&c.u==b)return{El:a,Fl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{El:a,Fl:b,result:2};return{El:a,Fl:b,result:3}},ppa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.w&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.w=0,T3(a.B,b,c,d))},qpa=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.u=d.time;0==d.type?ppa(a,d.Xu,d.Yu,b):1==d.type&&a.A&496&&T3(a.C,d.Xu,d.Yu,b)}a.o.length=0},U3=function(){this.o=0},V3=function(){this.u=this.A=this.o=0},W3=function(){this.timestamp=this.Yd=0},X3=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new W3}this.o=this.u=this.row=0;this.style=new U3;this.B=a;this.w=0},Y3=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.B.u+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.A[m][q];
if(0!=t.Yd){0==c&&(c=m,d=q);n=String.fromCharCode(t.Yd);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Yd||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.u+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],t=q.Yd,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32==m||0==t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},vpa=function(a,b){switch(a){case 0:return rpa[(b&127)-32];
case 1:return spa[b&15];case 2:return tpa[b&31];case 3:return upa[b&31]}return 0},Z3=function(a){return a.A[a.row][a.u]},$3=function(a,b,c){2<=b&&1<a.u&&(--a.u,Z3(a).Yd=0);
var d=Z3(a);d.timestamp=a.B.u+0;d.Yd=vpa(b,c);32>a.u&&a.u++},a4=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].fg(a.A[c+e][f])},b4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},c4=function(a){a.row=0<a.o?a.o:1;
a.u=1;b4(a,0,15)},d4=function(a){this.w=a;
this.B=0;this.style=new U3;this.C=new X3(a);this.D=new X3(a);this.G=new X3(a);this.u=this.C;this.A=this.D;this.o=this.u},e4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:Y3(d,c),c4(a.u),c4(a.A),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.w.mode=1<<d.w;e?d.u=1:d.o!=b&&(d.o>b?(Y3(d,c),b4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},f4=function(a){a.style.set(1);
a.o=a.A;a.o.o=0;a.o.style=a.style;a.w.mode=1<<a.o.w},g4=function(a){a.style.set(4);
a.o=a.G;a.o.style=a.style;a.w.mode=1<<a.o.w},Q3=function(a){this.u=a;
this.o=new V3;this.B=0;this.A=new d4(a);this.C=new d4(a);this.w=this.A},T3=function(a,b,c,d){a.o.update();
b=opa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.El;c=b.Fl;if(32<=e||!e)a.u.mode&a.u.A&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.w.o,b&96&&$3(a,0,b),c&96&&$3(a,0,c),0!=b&&0!=c&&3==a.style.o&&Y3(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.A=e,b.u=c,b.o=2,b=e&8?a.C:a.A,a.w=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.o?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.o?1:0))&a.u.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;a4(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));b4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:$3(b.o,0,32);break a;case 48:57==c?(d=b.o,Z3(d).Yd=0,32>d.u&&d.u++):$3(b.o,1,c&15)}break;case 2:c&32&&$3(b.o,2,c&31);break;case 3:c&32&&$3(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:f4(b);break;case 33:d=
b.o;1<d.u&&(--d.u,Z3(d).Yd=0);break;case 36:d=b.o;b=Z3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.A[a][c]==b){for(;32>=c;c++)d.A[a][c].reset();break}break;case 37:e4(b,2,d);break;case 38:e4(b,3,d);break;case 39:e4(b,4,d);break;case 40:$3(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.w.mode=1<<b.o.w;break;case 42:d=b.G;d.o=15;d.style.set(4);c4(d);g4(b);break;case 43:g4(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:Y3(a,d)}b4(a,0,15);break;case 45:b:{a=
b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;Y3(a,d);a4(a,b,b+1,a.o-1);b4(a,a.row,1)}break;case 46:b4(b.A,0,15);break;case 47:Y3(b.u,d),b.A.updateTime(b.w.u+0),d=b.A,b.A=b.u,b.u=d,f4(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},h4=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.dd){var n=f[1],q=f[2],t=f[3];l.getAttribute("p");var u=g.Dp();l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");t.getAttribute("t");f=u?g.Ld("DIV"):g.Ld("RUBY");l=l.textContent;var z=g.Ld("SPAN");z.textContent=l;f.appendChild(z);n.getAttribute("p");z=u?g.Ld("DIV"):g.Ld("RP");l=n.textContent;z.textContent=l;f.appendChild(z);k=k[q.getAttribute("p")];l=q.textContent;q=u?g.Ld("DIV"):g.Ld("RT");q.textContent=l;f.appendChild(q);l=k.dd;if(10==l||11==l||12==l||13==l||14==l)if(g.kh(q,"text-emphasis-style",
"filled circle"),g.kh(q,"text-emphasis-color","currentcolor"),g.kh(q,"webkit-text-emphasis","filled circle"),k.dd==k.dd==11||13==k.dd)g.kh(q,"webkit-text-emphasis-position","under left"),g.kh(q,"text-emphasis-position","under left");q=!0;if(4==k.dd||7==k.dd||12==k.dd||14==k.dd)g.kh(f,"ruby-position","over"),g.kh(f,"-webkit-ruby-position","before");else if(5==k.dd||6==k.dd||11==k.dd||13==k.dd)g.kh(f,"ruby-position","under"),g.kh(f,"-webkit-ruby-position","after"),q=!1;t.getAttribute("p");l=t.textContent;
t=u?g.Ld("DIV"):g.Ld("RP");t.textContent=l;f.appendChild(t);u&&(u=q,g.kh(f,{display:"inline-block",position:"relative"}),t=f.firstElementChild.nextElementSibling,g.kh(t,"display","none"),t=t.nextElementSibling,g.kh(t,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.kh(f.lastElementChild,"display","none"),u?(g.kh(f,"padding-top","0.6em"),g.kh(t,"top","0")):(g.kh(f,"padding-bottom","0.6em"),g.kh(t,"bottom",
"0")));return new F3(a,b,e,c,f,d,m)}switch(m.dd){case 9:case 10:m.we=1;break;case 11:m.we=2;break;case 12:m.we=3;break;case 13:m.we=4;break;case 14:m.we=5}return new F3(a,b,e,c,l.textContent||"",d,m)},i4=function(){g.A.apply(this,arguments)},j4=function(a){i4.call(this);
this.A={};this.H={};this.J={};this.B="_"+H3++;this.C=a;this.G={};this.u=this.o=null;this.D=!0},k4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},l4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},m4=function(a,b){var c=k4(a,b);
return void 0!=c?c:null},o4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return n4.test(c),c},p4=function(a,b){var c={},d=b.getAttribute("ws");
g.Pa(c,d?a.J[d]:a.C);d=m4(b,"mh");null!=d&&(c.Yq=d);d=m4(b,"ju");null!=d&&(c.textAlign=d);d=m4(b,"pd");null!=d&&(c.xe=d);d=m4(b,"sd");null!=d&&(c.SA=d);d=o4(b,"wfc");null!=d&&(c.windowColor=d);d=k4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},q4=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Pa(c,a.H[d]);d=m4(b,"ap");null!=d&&(c.Zf=d);d=k4(b,"cc");null!=d&&(c.Sl=d);d=k4(b,"ah");null!=d&&(c.Se=d);d=k4(b,"rc");null!=d&&(c.Lk=d);d=k4(b,"av");null!=d&&(c.Lg=d);return c},r4=function(a,b,c,d){var e={};
g.Pa(e,q4(a,b));g.Pa(e,p4(a,b));d?g.Yb(e,a.C)?(d=a.B,e=a.C):d="_"+H3++:d=b.getAttribute("id")||"_"+H3++;a=k4(b,"t")+c;b=k4(b,"d")||0x8000000000000;if(2==e.xe||3==e.xe)c=e.Lk,e.Lk=e.Sl,e.Sl=c;return new G3(a,b,0,d,e)},s4=function(a,b,c,d,e,f,k){K3.call(this,a,b,c,d,e,f,k);
this.type=1},t4=function(a,b,c){this.D=c;
this.version=this.C=this.w=this.o=0;this.u=new DataView(a);this.A=[]},u4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},v4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},w4=function(a,b){i4.call(this);
this.u=a;this.track="CC3"==b.A?4:0;this.o=new R3;this.o.A=1<<this.track},y4=function(a){if("string"===typeof a)return!1;
a=new t4(a,8,0);return x4(a)},x4=function(a){if(!(a.o<a.u.byteLength)||1380139777!=v4(a))return!1;
a.version=u4(a);if(1<a.version)return!1;u4(a);u4(a);u4(a);return!0},z4=function(a,b,c,d,e,f,k){K3.call(this,a,b,c,d,e,f,k);
g.L(this.element,"ytp-caption-window-rollup");this.type=2;this.J=[];this.N=this.K=this.ia=0;this.S=NaN;this.za=0;this.Ea=null;this.ga=new g.J(this.DL,433,this);g.B(this,this.ga);g.kh(this.element,"overflow","hidden")},wpa=function(a,b){return(a.C?b.offsetHeight:b.offsetWidth)+1},xpa=function(a){if(isNaN(a.S)){var b=a.w.Sl;
if(b){var c=g.Ld("SPAN");g.Vd(c,"\u2013".repeat(b));g.kh(c,L3(a,a.w.wb));a.D.appendChild(c);a.S=c.offsetWidth;a.D.removeChild(c)}else a.S=0}return a.S},ypa=function(a,b){if(!b)return"";
a.C&&1!=a.B.params.SA&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},A4=function(a){a.J=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.B.params.Lk,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.K=d;a.N=Math.max(xpa(a),a.za,wpa(a,a.D))},zpa=function(a,b){A4(a);
var c=a.J.reduce(function(e,f){return(a.C?f.offsetWidth:f.offsetHeight)+e},0);
c=a.K-c;if(c!=a.ia){var d=0<c&&0==a.ia;b||isNaN(c)||d||(g.L(a.element,"ytp-rollup-mode"),g.Xm(a.ga));g.kh(a.D,"transform",ypa(a,c));a.ia=c}A4(a)},B4=function(){i4.call(this)},C4=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Re=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType){q=new F3(b,c,d,e.id,q.nodeValue,f||0<n,g.Wb(l)?void 0:l);m.push(q);var t=e;g.B(t,q);t.o.push(q)}else t={},g.Pa(t,l),C4(a,b,c,d,e,!0,q,t,m)}},D4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+parseFloat(c.value);return 1E3*a},E4=function(a,b,c,d){d=Object.assign({Yq:0},d);
return new G3(a,b,c,"_"+H3++,d)},F4=function(a){g.A.call(this);
this.u=a;this.o=null},I4=function(a){g.VQ.call(this,a);
this.A=a.P();this.T=a.getVideoData();this.ra=g.jL(a);this.S=a;var b=null,c=g.Mn("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.wn(c));this.ea=b;this.w={wb:{}};this.C={wb:{}};this.J=[];this.U={};this.X={};this.K=!1;this.ga=g.XQ(this.T,this.S);this.xa=!!this.T.captionTracks.length;this.ya=!!this.T.sj;this.ba="3"==this.A.controlsType;b=a.app.B;c=!(!b||!b.Zk());this.oa=!(!b||!b.Mh());this.B=this.ba&&c&&!this.ga;this.H=!this.B&&this.ba&&this.oa&&this.ga;this.u=this.D=this.G=this.V=this.sa=
null;this.da=new F4(this.A);g.B(this,this.da);c=b=this.o=null;this.B||(b=new g.Um(this.lB,void 0,this),g.B(this,b),c=new g.J(this.hN,2E3,this),g.B(this,c));this.aa=b;this.ia=c;this.N=new g.R(this);g.B(this,this.N);this.B||this.N.M(a,"resize",this.Gt);this.N.M(a,"onPlaybackAudioChange",this.iJ);this.N.M(a,g.tE("captions"),this.JF,this);this.N.M(a,"crx_captions",this.KF,this);G4(this,H4(this,"display-settings")||{})},J4=function(a){if(1==a.A.dg||1==a.T.dg||"alwayson"==g.XC(a.T,"yt:cc"))return!0;
if(2==a.A.dg){var b=H4(a,"module-enabled");if(null!=b)return!!b}if(a.T.captionTracks.length)var c=a.player.getAudioTrack().tp;return"ON"==c||"on"==g.XC(a.T,"yt:cc")},K4=function(a,b){if(a.o&&(void 0===b||!b)||!a.T.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.im||"FORCED_ON"==c.tp},M4=function(a,b){if(a.u){if(a.D&&a.D.o)return a.D.o;
var c=b;c||(c=a.ya?!1:a.xa?!1:!0);c=t3(a.u.u,c);for(var d=[a.T.captionsLanguagePreference,a.A.captionsLanguagePreference,g.XC(a.T,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(s3(c[f])==d[e])return c[f];return a.D&&a.D.Ep?a.D.Ep:(d=c.find(function(k){return k.isDefault}))?d:c[0]||L4(a)}return null},L4=function(a){return a.D&&a.D.im},N4=function(a){var b=L4(a);
return!!b&&a.o==b},O4=function(a,b){for(var c=a.S.app.B.Za().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},Q4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.K=c,a.K&&P4(a,"module-enabled",!!b));a.o=b;K4(a)&&(a.o=L4(a));a.load()},Apa=function(a,b){var c=a.ra.getVideoContentRect(!0).height;
if(!c)return null;var d=a.ra.getPlayerSize();switch(null!=b.params.Yq?b.params.Yq:1<b.o.length?1:0){case 1:return new s4(b,a.w,a.C,c,d.width,d.height,a.A.experiments);case 2:return new z4(b,a.w,a.C,c,d.width,d.height,a.A.experiments);default:return new K3(b,a.w,a.C,c,d.width,d.height,a.A.experiments)}},G4=function(a,b,c){var d=R4.wb;
a.w={};g.Pa(a.w,R4);a.w.wb={};g.Pa(a.w.wb,d);a.C={wb:{}};var e=b.backgroundOverride?a.C:a.w,f=b.background||d.background;n4.test(f);e.wb.background=f;e=b.colorOverride?a.C:a.w;f=b.color||d.color;n4.test(f);e.wb.color=f;e=b.windowColorOverride?a.C:a.w;f=b.windowColor||R4.windowColor;n4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.w;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.wb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.w;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.wb.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.w;e=b.fontStyle;null==e&&(e=d.bold&&d.Re?3:d.bold?1:d.Re?2:0);f=f.wb;switch(e){case 1:f.bold=!0;delete f.Re;break;case 2:delete f.bold;f.Re=!0;break;case 3:f.bold=!0;f.Re=!0;break;default:delete f.bold,delete f.Re}e=b.textOpacityOverride?a.C:a.w;f=b.textOpacity;null==f&&(f=d.textOpacity);e.wb.textOpacity=f;e=b.windowOpacityOverride?a.C:a.w;f=b.windowOpacity;null==f&&(f=R4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.C:a.w;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.wb.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.w;f=b.fontFamily;null==f&&(f=d.fontFamily);e.wb.fontFamily=f;a.loaded&&a.Gt();c&&P4(a,"display-settings",b)},T4=function(a,b){if(b&&!a.G){var c=I3({xe:0,
lang:"en-GB"});a.G=[c,new F3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.xL(a.player,a.G)}else!b&&a.G&&(S4(a,a.G),a.G=null)},S4=function(a,b){g.MU(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.bb(this.J,c)},a);
a.aa.ii()},H4=function(a,b){if(!a.ea)return null;
try{var c=a.ea.get(b)}catch(d){a.ea.remove(b)}return c},P4=function(a,b,c){if(a.ea)try{a.ea.set(b,c)}catch(d){}};
g.Zz.prototype.jr=g.ca(11,function(a){return a?this.toString()==a.toString():!1});
g.$u.prototype.xm=g.ca(10,function(a){return(a=this.jg(a))?a.o:0});
g.sz.prototype.xm=g.ca(9,function(){return 0});
g.Gt.prototype.tj=g.ca(8,function(){for(var a=g.xd(document,"track",void 0,this.o),b=0;b<a.length;b++)g.Qd(a[b])});
g.LS.prototype.tj=g.ca(7,function(){this.o.tj()});
g.Gt.prototype.Zk=g.ca(6,function(){return!!this.o.textTracks});
g.LS.prototype.Zk=g.ca(5,function(){return this.o.Zk()});
g.Gt.prototype.oj=g.ca(4,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.LS.prototype.oj=g.ca(3,function(a){this.o.oj(a)});
g.wt.prototype.Mh=g.ca(2,function(){});
g.Gt.prototype.Mh=g.ca(1,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.LS.prototype.Mh=g.ca(0,function(){return this.o.Mh()});
var Bpa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,n4=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(v3,g.A);v3.prototype.Pz=function(){return!1};
v3.prototype.Z=function(){this.Mg();g.A.prototype.Z.call(this)};
g.r(w3,v3);w3.prototype.Vq=function(a,b,c){b=this.Lj(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Mg();this.o=g.tp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
w3.prototype.Wq=function(a){if(this.A)for(var b=g.p(this.A.captionTracks),c=b.next();!c.done;c=b.next())u3(this.u,c.value);a()};
w3.prototype.Lj=function(a,b){var c=a.G,d={fmt:b};if("srv3"==b||"3"==b)g.Dp()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.o&&(d.tlang=s3(a));return g.bp(c,d)};
w3.prototype.Mg=function(){this.o&&this.o.abort()};
x3.prototype.contains=function(a){a=g.lb(this.o,a);return 0<=a||0>a&&1==(-a-1)%2};
x3.prototype.length=function(){return this.o.length/2};
g.r(y3,g.A);g.h=y3.prototype;g.h.Z=function(){g.A.prototype.Z.call(this);this.u&&this.u.cancel()};
g.h.Wx=function(){z3(this,this.A.getCurrentTime())};
g.h.reset=function(){this.B=new x3;this.u&&(this.u.cancel(),this.u=null)};
g.h.fx=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.Pf(a);!a||this.u||this.o&&30<this.o.startTime-this.A.getCurrentTime()||(a=this.o,a=a.o.Di(a),a.o[0].duration?(this.B.contains(a.o[0].u)||A3(this,a),this.o=g.Ta(a.o)):!g.U(this.U.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.A.ub()<this.A.getCurrentTime()&&z3(this,this.A.getCurrentTime()));this.G.start()};
g.h.yL=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.xz(a);c?(a=g.az(this.w,this.J,{}),b=this.w,g.Xy(b.u,a,c),b.requestId=a.get("req_id"),A3(this,this.w)):(b||null===this.D||(c=this.w.o[0],this.C?this.D(a.response,1E3*(c.startTime+this.A.ub())):this.D(a.responseText,1E3*(c.startTime+this.A.ub()))),this.u=this.w=null)};
g.r(B3,v3);g.h=B3.prototype;g.h.Vq=function(a,b,c){this.Mg();b=mpa(this,a.getId());b||(b=a.u,b=this.o.u?D3(this,b,"386"):D3(this,b));if(b){var d=1E3*(b.index.xm(b.index.oe())-b.index.Oc(b.index.oe()));this.A=new y3(new g.Sy,this.D,b,function(e,f){c(e,a,f,d)},this.C||g.Ks(b.info),(0,g.x)(function(){this.A&&this.A.reset();
this.w=!0},this))}};
g.h.Pz=function(){var a=this.w;this.w=!1;return a};
g.h.Wq=function(a){var b;this.C?b=[new g.Zz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Zz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.u?C3(this,"386"):C3(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())u3(this.u,c.value);a()};
g.h.Mg=function(){this.A&&(this.A.dispose(),this.A=null)};
g.h.Lj=function(){return""};
g.r(E3,v3);E3.prototype.Vq=function(a,b,c){b=this.Lj(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Mg();this.o=g.tp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
E3.prototype.Wq=function(a){var b=this.w,c={type:"list",tlangs:1,v:this.A,vssids:1};this.C&&(c.asrs=1);b=g.bp(b,c);c=(0,g.x)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.p(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
u3(this.u,new g.Zz({languageCode:f,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:u,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),q=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:t},this.D[l.languageCode]=l.languageName,this.B.push(l)}a()},this);
this.Mg();this.o=g.tp(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
E3.prototype.Lj=function(a,b){var c=this.w,d={v:this.A,type:"track",lang:a.u,name:a.getName(),kind:a.w,fmt:b};a.o&&(d.tlang=s3(a));return c=g.bp(c,d)};
E3.prototype.Mg=function(){this.o&&this.o.abort()};var npa=["left","right","center","justify"];var R4={windowColor:"#080808",windowOpacity:0,textAlign:2,Zf:7,Se:50,Lg:100,wb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(F3,g.qE);F3.prototype.toString=function(){return g.qE.prototype.toString.call(this)};g.r(G3,g.qE);G3.prototype.toString=function(){return g.qE.prototype.toString.call(this)};
var H3=0;g.r(K3,g.T);g.h=K3.prototype;g.h.LG=function(a,b){var c=g.Bh(this.element,this.element.parentElement);this.ra=a-c.x;this.xa=b-c.y;g.L(this.element,"ytp-dragging")};
g.h.KG=function(a,b){var c=g.Eh(this.element),d=a-this.ra-.02*this.Ma,e=b-this.xa-.02*this.La,f=(d+c.width/2)/this.ba*3;f=Math.floor(g.kd(f,0,2));var k=(e+c.height/2)/this.ya*3;k=Math.floor(g.kd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ba;d=100*g.kd(d,0,1);c=(e+k/2*c.height)/this.ya;c=100*g.kd(c,0,1);this.B.params.Zf=l;this.B.params.Lg=c;this.B.params.Se=d;this.w.Zf=l;this.w.Lg=c;this.w.Se=d;this.pA()};
g.h.JG=function(){g.hn(this.element,"ytp-dragging")};
g.h.pA=function(){this.Jh(this.G)};
g.h.Jh=function(a){var b=Math.min(this.Xv(),this.ba),c=this.Wv(),d="";3==this.B.params.xe&&(d="rotate(180deg)");g.kh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.hp(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.w.Se+2;d=this.w.Zf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.D.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.w.Lg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.kh(this.element,a)};
g.h.hp=function(a){var b;for(b=0;b<a.length&&a[b]==this.G[b];b++);if(this.V||this.G.length>b)b=0,this.V=!1,this.G=[],this.H=this.da=this.X=null,g.Od(this.D);for(;b<a.length;b++)O3(this,a[b])};
g.h.Xv=function(){return 0};
g.h.Wv=function(){return 0};
g.h.toString=function(){return g.T.prototype.toString.call(this)};P3.prototype.B=function(){};R3.prototype.clear=function(){this.w=this.u=this.mode=0;this.o=[];this.reset()};
R3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var S3=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];U3.prototype.set=function(a){this.o=a};
U3.prototype.get=function(){return this.o};
V3.prototype.clear=function(){this.o=0};
V3.prototype.update=function(){this.o=2==this.o?1:0};
V3.prototype.matches=function(a,b){return 0!=this.o&&a==this.A&&b==this.u};
W3.prototype.fg=function(a){this.Yd=a.Yd;this.timestamp=a.timestamp};
W3.prototype.reset=function(){this.timestamp=this.Yd=0};
X3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.A[b][c].timestamp=a};
X3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0==d.Yd?a+"_":a+String.fromCharCode(d.Yd)}a+="\n"}return a};
X3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.w=a;this.o=0;this.u=this.row=1};
var rpa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],spa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],tpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],upa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];d4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.A=this.D;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
Q3.prototype.reset=function(a){this.B=a;this.o.clear();this.w=this.A;this.A.reset(a,0);this.C.reset(a,1)};g.r(i4,g.A);i4.prototype.reset=function(){};g.r(j4,i4);j4.prototype.reset=function(){this.G={};this.u=this.o=null;this.D=!0};
j4.prototype.w=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Pa(l,this.A[m]);m=l4(c,"b");null!=m&&(l.bold=
m);m=l4(c,"i");null!=m&&(l.Re=m);m=l4(c,"u");null!=m&&(l.underline=m);m=m4(c,"et");null!=m&&(l.charEdgeStyle=m);m=m4(c,"of");null!=m&&(l.offset=m);m=o4(c,"bc");null!=m&&(l.background=m);m=o4(c,"ec");null!=m&&(l.dv=m);m=o4(c,"fc");null!=m&&(l.color=m);m=m4(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=k4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=k4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=k4(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=m4(c,"rb");null!=m&&10!=m&&0!=m&&(l.dd=10<m?m-1:m);
m=m4(c,"hg");null!=m&&(l.AE=m);c=m4(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.we=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.J[d]=p4(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=q4(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=r4(this,d,e,!1);g.B(this,this.o);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.B;m=!!l4(d,"a");n=(k4(d,"t")||0)+n;var q=k4(d,"d")||5E3;m||(!this.D&&this.u&&this.u.windowId==l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"==this.u.text&&(this.u.text=""));var t=m?6:5,u=this.A[d.getAttribute("p")],z=[].concat(g.ea(d.childNodes));z.length&&(this.D=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var D=z[C],G=void 0;0<C&&(m=!0);var K=void 0;1==D.nodeType&&(K=D);if(K&&"s"==K.tagName){if((D=this.A[K.getAttribute("p")])&&D.dd&&(1==D.dd?(D=z.slice(C,
C+4),4==D.length&&(G=h4(n,q,l,m,t,D,this.A),C+=3)):G=h4(n,q,l,m,t,[K],this.A)),!G){var E=K;G=n;K=q;D=l;var N=m,ka=t,na=E.textContent?E.textContent:"",Ia=this.A[E.getAttribute("p")];E=k4(E,"t")||0;G=new F3(G+E,K-E,ka,D,na,N,Ia)}}else G=new F3(n,q,t,l,D.textContent||"",m,u);k.push(G);this.u=G}if(0<k.length)for(k[0].windowId==this.B&&(this.o=r4(this,d,e,!0),g.B(this,this.o),c.push(this.o)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,l=this.o,g.B(l,k),l.o.push(k),c.push(k)}e=
c}else e=[];return e};g.r(s4,K3);s4.prototype.hp=function(a){var b=this.B.o;K3.prototype.hp.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Pa(d,c.o);g.Pa(d,Cpa);var e=c.o;var f=d}O3(this,c,d)}};
var Cpa={yE:!0};g.r(t4,P3);t4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+H3++;c=c/1E3-this.D;d=d/1E3-this.D;a=new G3(c,d-c,5,f,{textAlign:0,Zf:0,Se:2.5*b,Lg:5.33*a});e=new F3(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.r(w4,i4);w4.prototype.w=function(a){a=new t4(a,a.byteLength,this.u);if(x4(a)){for(;a.o<a.u.byteLength;)for(0==a.version?a.w=v4(a)*(1E3/45):1==a.version&&(a.w=4294967296*v4(a)+v4(a)),a.C=u4(a);0<a.C;a.C--){var b=u4(a),c=u4(a),d=u4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.w,type:this.track,Xu:c,Yu:d,order:b.o.length}))}qpa(this.o,a);return a.A}return[]};
w4.prototype.reset=function(){this.o.clear()};g.r(z4,K3);g.h=z4.prototype;g.h.pA=function(){g.Ym(this.ga)};
g.h.DL=function(){g.hn(this.element,"ytp-rollup-mode");this.Jh(this.Ea,!0)};
g.h.Wv=function(){return this.C?this.N:this.K};
g.h.Xv=function(){return this.C?this.K:this.N};
g.h.Jh=function(a,b){this.Ea=a;if(this.B.params.Lk){for(var c=0,d=0;d<this.G.length&&c<a.length;d++)this.G[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.G.concat(a.slice(c)));this.za=this.N;this.K=this.N=0;K3.prototype.Jh.call(this,a);zpa(this,b);K3.prototype.Jh.call(this,a)}else K3.prototype.Jh.call(this,a)};g.r(B4,i4);
B4.prototype.w=function(a,b){for(var c=[],d=a.split(Dpa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Epa.test(f)){var l=U4.exec(f);if(l&&4<=l.length){var m=D4(l[1]),n=D4(l[2])-m;m+=k;var q,t=q=void 0,u=void 0,z=void 0,C=(l=l[3])?l.split(" "):[];l={textAlign:2};C=g.p(C);for(var D=C.next();!D.done;D=C.next())if(D=D.value.split(":"),2==D.length){var G=D[1];switch(D[0]){case "line":D=G.split(",");D[0].endsWith("%")&&(z=D[0],l.Lg=Number.parseInt(z,10),2==D.length&&(u=D[1].trim()));break;case "position":D=G.split(",");
t=D[0];l.Se=Number.parseInt(t,10);2==D.length&&(q=D[1].trim());break;case "align":switch(G){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Lg=100,u||(u="end"));if(!t)switch(l.textAlign){case 0:l.Se=0;break;case 1:l.Se=100;break;default:l.Se=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(q){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Zf=0>t||8<t?7:t;q=l;f=f.substring(U4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=E4(m,n,5,t),n=new F3(m,n,5,k.id,q,!1,g.Wb(f)?void 0:f),c.push(k),c.push(n),g.B(k,n),k.o.push(n);else for(u=q.split(Fpa),1==u.length?(q=5,t=E4(m,n,q,t)):(z=q=6,t=Object.assign({Sl:32},t),t=new G3(m,n,z,"_"+H3++,t)),c.push(t),z=m,l=0;l<u.length;l++)C=u[l],0==l%2?(D=g.o0("<html>"+C+"</html>"),D.getElementsByTagName("parsererror").length?
(G=D.createElement("span"),G.appendChild(D.createTextNode(C))):G=D.firstChild,C4(this,z,n-(z-m),q,t,0<l,G,f,c)):z=D4(C)+k}U4.lastIndex=0}}return c};
var Epa=/^NOTE/,Dpa=/(?:\r\n|\r|\n){2,}/,U4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Fpa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(F4,g.A);F4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
F4.prototype.reset=function(){this.o&&this.o.reset()};
F4.prototype.Z=function(){this.clear();g.A.prototype.Z.call(this)};g.r(I4,g.VQ);g.h=I4.prototype;g.h.Z=function(){if(this.B||this.H){var a=this.S.app.B;a&&a.tj()}else T4(this,!1);g.VQ.prototype.Z.call(this)};
g.h.load=function(){g.VQ.prototype.load.call(this);var a=!g.U(this.A.experiments,"web_player_captions_track_list_changed_killswitch");this.D=this.player.getAudioTrack();if(this.u)this.o&&(this.da.clear(),this.B?O4(this,!0):3!=this.player.getPresentingPlayerType()&&this.u.Vq(this.o,"srv3",(0,g.x)(this.mM,this)),!a||this.B||this.H||N4(this)||this.player.ma("captionschanged",r3(this.o))),a||(this.o&&!N4(this)?this.player.ma("captionschanged",r3(this.o)):this.player.ma("onCaptionsTrackListChanged"));
else{var b;this.ga?b=new B3(this.T.la,this.player):this.xa?b=new w3(this.A,this.T,this.player.getAudioTrack()):b=new E3(this.T.sj,this.T.videoId,this.T.captionsLanguagePreference||this.A.captionsLanguagePreference||g.XC(this.T,"yt:cc_default_lang")||this.A.Yb,this.T.qp,this.A);this.u=b;g.B(this,this.u);b.Wq((0,g.x)(this.lM,this))}};
g.h.unload=function(){this.B&&this.o?O4(this,!1):(this.ia&&g.Zm(this.ia),g.oS(this.player.app,"captions",void 0),this.J=[],this.u&&this.u.Mg(),this.da.clear(),this.G&&g.xL(this.player,this.G),this.Gt());g.VQ.prototype.unload.call(this);var a=g.S(this.player.app);a&&g.fJ(a.B);this.player.ma("captionschanged",{})};
g.h.create=function(){(this.ba?this.B||this.H:K4(this)||J4(this))&&this.load()};
g.h.lM=function(){var a;this.K||J4(this)?a=M4(this,this.K):K4(this)&&(a=L4(this));if(this.B||this.H){for(var b=t3(this.u.u,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.$z(e),srclang:s3(e),id:e.toString()};this.H||(f.src=this.u.Lj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Kd("TRACK",f))}a=this.S.app.B;a.oj(c);c=a.Za();this.oa&&this.N.M(c.textTracks,"change",this.nM)}else!this.o&&a&&Q4(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.nM=function(){for(var a=this.S.app.B.Za().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=t3(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.o:null)!=b&&Q4(this,b,!0)};
g.h.UN=function(){!this.o&&this.B||this.unload()};
g.h.mM=function(a,b,c,d){if(a){this.u.Pz()&&(this.J=[],g.oS(this.S.app,"captions",void 0),this.aa.ii(),this.da.reset());var e=this.da;c=c||0;d=d||0;if("string"!==typeof a){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.zv(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!y4(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<
m&&365>m){n=a[k++];var q=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if("string"!==typeof a){var u=a,z=c,C=d;if(!y4(u))throw Error("Invalid binary caption track data");e.o||(e.o=new w4(C,b));var D=e.o.w(u,z)}else{if("WEBVTT"==a.substring(0,6)){b=a;z=c;e.o||(e.o=new B4);var G=e.o.w(b,z);.01>Math.random()&&
g.oo(Error("Deprecated subtitles format in web player: WebVTT"));u=G}else b:{G=a;z=g.o0(G);if(!z||!z.firstChild){var K=Error("Invalid caption track data");K.params=G;throw K;}if("timedtext"==z.firstChild.tagName){if(3==parseInt(z.firstChild.getAttribute("format"),10)){if(!e.o){G={};if(C=s3(b))G.lang=C,Bpa.test(C)&&(G.xe=1);e.o=new j4(G,e.u)}u=e.o.w(z,c);break b}var E=Error("Unsupported subtitles format in web player (Format2)");E.params=G;throw E;}if("transcript"==z.firstChild.tagName){var N=Error("Unsupported subtitles format in web player (Format1)");
N.params=G;throw N;}var ka=Error("Invalid caption track data");ka.params=G;throw ka;}D=u}var na=D}catch(Ia){g.O(Ia),e.clear(),na=[]}else na=[];g.xL(this.player,na);!this.K||this.H||N4(this)||g.zy(this.A)||g.Ay(this.A)||(g.Zm(this.ia),na=I3({Zf:0,Se:5,Lg:5,Lk:2,textAlign:0,xe:0,lang:"en-GB"}),this.V=[na],e=["Click "," for settings"],this.sa||(D=new g.uu(g.GN()),g.B(this,D),this.sa=D.element),D=na.end-na.start,(b=g.$z(this.o))&&this.V.push(new F3(na.start,D,0,na.id,b)),this.V.push(new F3(na.start,D,
0,na.id,e[0]),new F3(na.start,D,0,na.id,this.sa,!0),new F3(na.start,D,0,na.id,e[1],!0)),g.xL(this.player,this.V),g.Xm(this.ia));!this.K||this.H||N4(this)||(P4(this,"module-enabled",!0),this.D&&(this.D.o=this.o),(na=g.S(this.player.app))&&g.fJ(na.B));this.K=!1}};
g.h.JF=function(a){this.J.push(a);this.aa.ii()};
g.h.KF=function(a){g.bb(this.J,a);this.u instanceof B3&&this.u.C&&g.MU(this.player.app,[a],void 0);this.aa.ii()};
g.h.aN=function(a){if(a instanceof G3){var b=this.U[a.id];b&&b.B!=a&&(b.dispose(),delete this.U[a.id],b=null);b||(b=Apa(this,a))&&(this.U[a.id]=b)}else b=a.windowId,this.X[b]||(this.X[b]=[]),this.X[b].push(a)};
g.h.hN=function(){S4(this,this.V);this.V=null};
g.h.lB=function(){this.aa.stop();g.Xb(this.X);this.J.sort(g.sE);var a=this.J;if(this.G){var b=(0,g.Rd)(a,function(c){return-1==this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.aN,this);g.Ib(this.U,function(c,d){this.X[d]?(c.element.parentNode||g.BL(this.player,c.element,4),c.Jh(this.X[d])):(c.dispose(),delete this.U[d])},this)};
g.h.mN=function(){G4(this,{},!0);g.U(this.A.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ma("captionssettingschanged")};
g.h.ND=function(){var a=R4.wb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Re?3:a.bold?1:a.Re?2:0,textOpacity:a.textOpacity,windowColor:R4.windowColor,windowOpacity:R4.windowOpacity};var b=H4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.qB=function(a,b){var c={};g.Pa(c,H4(this,"display-settings"));g.Pa(c,a);G4(this,c,b);this.player.ma("captionssettingschanged")};
g.h.Gt=function(){!this.B&&this.loaded&&(g.Ib(this.U,function(a,b){a.dispose();delete this.U[b]},this),this.lB())};
g.h.Ac=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.kd(b,-2,4);this.qB({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&Q4(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.A.xb&&P4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.La(b))break;if(g.Wb(b)){Q4(this,null,!0);break}for(var d=t3(this.u.u,!0),e=0;e<d.length;e++){var f=d[e];f.u!=b.languageCode||c&&f.A!=b.languageName||(c=b.translationLanguage?kpa(f,b.translationLanguage):
f)}!c||c==this.o&&this.loaded||Q4(this,c,!0)}else return this.loaded&&this.o&&!N4(this)?r3(this.o):{};return"";case "tracklist":return this.u?(0,g.H)(t3(this.u.u,!(!b||!b.includeAsr)),function(k){return r3(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||T4(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.A.xb&&a.push("stickyLoading");return a};
g.h.IF=function(){var a=this.o;return a?{cc:a.C}:{}};
g.h.MN=function(){this.loaded&&this.o&&!N4(this)?(P4(this,"module-enabled",!1),this.unload(),K4(this,!0)&&Q4(this,L4(this),!1)):Q4(this,N4(this)||!this.o?M4(this,!0):this.o,!0)};
g.h.iJ=function(){var a=N4(this);K4(this,a)?Q4(this,this.player.getAudioTrack().im,!1):this.T.captionTracks.length&&(this.loaded&&this.unload(),(this.ba?this.B||this.H:K4(this)||J4(this))&&(a?Q4(this,M4(this),!1):this.load()))};g.kR.captions=I4;})(_yt_player);
